#! /bin/bash
# BRIX ; 20160313
# B4P x RVZ // RED WEAPON PROXIES
# Concatenation d'un ensemble de fichiers vidéos ProRes en un seul

# accéder au dossier proxies
echo "Où est le dossier Proxies?"
read ProxiesPath

# accéder au dossier contenant le clip
# d'après Nejib
echo "Où se trouve le clip ?"
read ClipPath
cd $ClipPath

# détermination du clipname parmi les éléments du dossier
clipnames=$(basename $ClipPath/*.mov)
# déterminer le clipname final selon le premier élément de la liste et en éliminant l'extension
clipname=$(echo ${clipnames%%.*} | awk {'print $1'})
proxyname=$(echo $clipname | sed 's/.\{4\}$//g')

# vider le fichier temporaire medias.txt pour éviter l'addition des lignes, puis repérer les différents éléments
rm $ProxiesPath/$clipname.txt
for f in $ClipPath/*.mov; do echo "file '$f'" >> $ProxiesPath/$clipname.txt; done

# obtenir un timecode pour un fichier donné et l'enregistrer
timecode=$(mediainfo $ClipPath/$clipname.mov | grep 'Time code of first frame'| awk {'print $NF'})
#timecode=$(ffprobe -v error -select_streams v:1 -show_entries stream_tags=timecode -of default=noprint_wrappers=1:nokey=1 $clipname.mov)
echo "Time code of first frame : " $timecode

# atteindre le dossier Proxies
cd $ProxiesPath

# concatener les éléments listés dans le fichier medias.txt
ffmpeg -f concat -i $ProxiesPath/$clipname.txt -vcodec copy -acodec copy -timecode $timecode $proxyname.mov

# ouvrir le dossier contenant les nouveaux médias
open $ProxiesPath

#	    problèmes à régler :
# - récurrence du processus sur l'ensemble des clips
# - mettre à jour selon l'arborescence du Redmag
# - ajouter l'info de ReelName automatiquement
# - trier les streams selon 0 = video ; 1 = audio ; 2 = data
