#! /bin/bash
# BRIX ; 20160316
# B4P x RVZ // RED WEAPON PROXIES
# Concatenation d'un ensemble de fichiers vidéos ProRes en un seul

##########################
## SOURCE & DESTINATION ##

# accéder au dossier proxies
echo "Drop Proxies folder (output)?"
read proxiespath

# accéder au dossier contenant le clip
echo "Drop Card Folder *.RDM"
read root
cd $root
# détermination du reelname à partir de la carte
reelname=$(basename ${root%%.*})


#############################
## DETERMINATION DES DATAS ##
for g in $root/*.RDC;
	do
		echo "file '$g'" >> $proxiespath/$reelname.txt;
#		duration=1
#		echo "duration :"$duration
#		duration2=1
#		echo "duration2 :"$duration2
#		durationts=1
#		echo "durationts :"$durationts

		#récupération de l'info clippath dans la valeur de la boucle
		clippath=$g
		
		# détermination du clipname parmi les éléments du dossier
		clipnames=$(basename $clippath/*.mov)

		# déterminer le clipname final selon le premier élément de la liste et en éliminant l'extension
		clipname=$(echo ${clipnames%%.*} | awk {'print $1'})
		proxyname=$(echo $clipname | sed 's/.\{4\}$//g')

		# vider le fichier temporaire medias.txt pour éviter l'addition des lignes, puis repérer les différents éléments
		rm $proxiespath/$clipname.txt
		for f in $clippath/*.mov; do echo "file '$f'" >> $proxiespath/$clipname.txt; done

		# obtenir un timecode pour un fichier donné et l'enregistrer
		timecode=$(mediainfo $clippath/$clipname.mov | grep 'Time code of first frame'| awk {'print $NF'})
		# déterminer la longueur du clip avec une loop 
		#	on doit travailler en opération une addition des durées des fichiers ProRes pour obtenir la durée finale
		unset duration2
		for f in $clippath/*.mov;
			do 
				echo $f
				duration=$(ffprobe -select_streams 1 -show_entries streams:stream=nb_frames $f | grep 'nb_frames'| awk -F"=" '{print $NF}')
				duration2=$(($duration2 + duration))
				echo $duration2
				echo "Proxy's duration : " $duration2 "frames"
#				>> $proxiespath/$clipname.txt;

		
			done

				# élimination de l'image de trop
				durationts=$(($duration2 -1))

		#timecode=$(ffprobe -v error -select_streams v:1 -show_entries stream_tags=timecode -of default=noprint_wrappers=1:nokey=1 $clipname.mov)
		echo "Time code of first frame : " $timecode
		echo "Durationts : " $durationts

#############
## CALCULS ##

		# atteindre le dossier Proxies
		cd $proxiespath

		# concatener les éléments listés dans le fichier medias.txt
		ffmpeg -f concat -i $proxiespath/$clipname.txt -vframes $durationts -vcodec copy -acodec copy -timecode $timecode $proxyname.mov
	done
done


# ouvrir le dossier contenant les nouveaux médias
open $proxiespath
